### ISSUE TITLE
Aioquic depency in plot_congestion.py

### ISSUE THREAD

**Issue by AurelienBuchet** [Aperence/linfo1341-work#2]
The current plot_congestion.py depens on the aioquic fork which is not mentionned. You should either 

1. Add it in the requirements and provide instructions to install it or 
2. As it only uses constants, define them directly in the file to remove the dependancy completly.

Option 2 is probably the best here as it avoid installing custom python packages that might conflit with the main aioquic package.

**Comment by Aperence** [comment]
Hi, 

Thanks for your suggestion, I opted for the second solution you proposed.
