### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by AurelienBuchet** [Aperence/linfo1341-work#3]
This issue regroup small typos/bugs that does not require their own issue.

## Usage bug in cca_single

In [scenarios/cca_single](scenarios/cca_single), the name variable is used in the usage error message before being defined resulting in the wrong message to be echoed.

## Typo in lab.conf

In [lab/lab.conf](lab/lab.conf), line 23 : 
\# this router will allow use to limit the bandwidth, as all requests will go through it
Should be 
\# this router will allow us to limit the bandwidth as all requests will go through it.

## Unstable ssh connection

I don't know if it is comming from my setup but I found the ssh connection very unstable making it nearly impossible to run the commands for the lab. The altenative solution was to directly launch a shell inside the container :

```
docker exec -it MAIN_CONTAINER_NAME /bin/bash
```

The name can be retreived with

```
docker ps | grep main
```

This could be added as an other way to connect if someone else experiences issues with the ssh.

## Missing text in "Starting simple : one client with CCA" solution

In the first bullet point of the solution, it seems that a sentence is missing.

## Missing command in "Stepping up : sharing bandwidth" solution

In the second paragraph, you mention that it is possible to activate the reno-friendly region for cubic but it seems that the command is missing.

**Comment by Aperence** [comment]
- moved name to the start of script
- Fixed typos
- added missing phrases for "Starting simple : one client with CCA" and "Stepping up : sharing bandwidth"
- added a troubleshooting section at the end of the lab README
